version: "3.4"

services:
  databasePostgres:
    image: "postgres:9.6-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_timeout
    ports:
      - "5432:5432"

  databaseMysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example